USE [BulkWriterTest]
GO
/****** Object:  Table [dbo].[MyDomainEntities]    Script Date: 9/12/2014 10:41:33 AM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MyDomainEntities]') AND type in (N'U'))
DROP TABLE [dbo].[MyDomainEntities]
GO
USE [master]
GO
/****** Object:  Database [BulkWriterTest]    Script Date: 9/12/2014 10:41:33 AM ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'BulkWriterTest')
DROP DATABASE [BulkWriterTest]
GO
/****** Object:  Database [BulkWriterTest]    Script Date: 9/12/2014 10:41:33 AM ******/
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'BulkWriterTest')
BEGIN
CREATE DATABASE [BulkWriterTest]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BulkWriterTest', SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BulkWriterTest_log', SIZE = 4096KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
END

GO
ALTER DATABASE [BulkWriterTest] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BulkWriterTest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BulkWriterTest] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BulkWriterTest] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BulkWriterTest] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BulkWriterTest] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BulkWriterTest] SET ARITHABORT OFF 
GO
ALTER DATABASE [BulkWriterTest] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BulkWriterTest] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [BulkWriterTest] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BulkWriterTest] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BulkWriterTest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BulkWriterTest] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BulkWriterTest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BulkWriterTest] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BulkWriterTest] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BulkWriterTest] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BulkWriterTest] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BulkWriterTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BulkWriterTest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BulkWriterTest] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BulkWriterTest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BulkWriterTest] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BulkWriterTest] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BulkWriterTest] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BulkWriterTest] SET RECOVERY FULL 
GO
ALTER DATABASE [BulkWriterTest] SET  MULTI_USER 
GO
ALTER DATABASE [BulkWriterTest] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BulkWriterTest] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BulkWriterTest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BulkWriterTest] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
EXEC sys.sp_db_vardecimal_storage_format N'BulkWriterTest', N'ON'
GO
USE [BulkWriterTest]
GO
/****** Object:  Table [dbo].[MyDomainEntities]    Script Date: 9/12/2014 10:41:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MyDomainEntities]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[MyDomainEntities](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](50) NULL,
	[LastName] [nvarchar](50) NULL,
 CONSTRAINT [PK_MyDomainEntities] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
USE [master]
GO
ALTER DATABASE [BulkWriterTest] SET  READ_WRITE 
GO
