//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

namespace BulkWriter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BulkWriter.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current mapping does not match a column in the destination table. The proposed source property is &apos;{0}&apos; and the proposed destination column is &apos;{1}&apos;..
        /// </summary>
        internal static string AutoDiscover_Mappings_MappingDoesNotMatchDbColumn {
            get {
                return ResourceManager.GetString("AutoDiscover_Mappings_MappingDoesNotMatchDbColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ordinal does not map to a name..
        /// </summary>
        internal static string EnumerableDataReader_GetName_OrdinalDoesNotMapToName {
            get {
                return ResourceManager.GetString("EnumerableDataReader_GetName_OrdinalDoesNotMapToName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name does not map to a ordinal..
        /// </summary>
        internal static string EnumerableDataReader_GetOrdinal_NameDoesNotMapToOrdinal {
            get {
                return ResourceManager.GetString("EnumerableDataReader_GetOrdinal_NameDoesNotMapToOrdinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ordinal does not map to a property..
        /// </summary>
        internal static string EnumerableDataReader_GetValue_OrdinalDoesNotMapToProperty {
            get {
                return ResourceManager.GetString("EnumerableDataReader_GetValue_OrdinalDoesNotMapToProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression must contain a MemberAccessExpression to a property (t =&gt; t.Property)..
        /// </summary>
        internal static string MapBuilderContext_ExtractPropertyInfo_InvalidPropertySelector {
            get {
                return ResourceManager.GetString("MapBuilderContext_ExtractPropertyInfo_InvalidPropertySelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided destination table cannot be an empty string..
        /// </summary>
        internal static string MapBuilderContext_ToDestinationTable_InvalidTableName {
            get {
                return ResourceManager.GetString("MapBuilderContext_ToDestinationTable_InvalidTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided colum name mapping cannot be an empty string..
        /// </summary>
        internal static string MapBuilderContextMap_ToColumnName_InvalidColumName {
            get {
                return ResourceManager.GetString("MapBuilderContextMap_ToColumnName_InvalidColumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided ordinal mapping cannot be less than 0..
        /// </summary>
        internal static string MapBuilderContextMap_ToColumnOrdinal_InvalidOrdinal {
            get {
                return ResourceManager.GetString("MapBuilderContextMap_ToColumnOrdinal_InvalidOrdinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided column size mapping cannot be less than 0..
        /// </summary>
        internal static string MapBuilderContextMap_ToColumnSize_InvalidColumnSize {
            get {
                return ResourceManager.GetString("MapBuilderContextMap_ToColumnSize_InvalidColumnSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided data type mapping cannot be an empty string..
        /// </summary>
        internal static string MapBuilderContextMap_ToDataTypeName_InvalidName {
            get {
                return ResourceManager.GetString("MapBuilderContextMap_ToDataTypeName_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided connection string cannot be an empty string..
        /// </summary>
        internal static string Mapping_CreateBulkWriter_InvalidConnectionString {
            get {
                return ResourceManager.GetString("Mapping_CreateBulkWriter_InvalidConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; is not set. Use the &apos;IsPropertySet&apos; method to check if a property has been set..
        /// </summary>
        internal static string MappingDestination_GetPropertyValue_PropertyNotSet {
            get {
                return ResourceManager.GetString("MappingDestination_GetPropertyValue_PropertyNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided ordinal cannot be less than 0..
        /// </summary>
        internal static string MappingSource_InvalidOrdinal {
            get {
                return ResourceManager.GetString("MappingSource_InvalidOrdinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied property is not declared on a type..
        /// </summary>
        internal static string PropertyInfoExtensions_PropertyNotDeclaredOnType {
            get {
                return ResourceManager.GetString("PropertyInfoExtensions_PropertyNotDeclaredOnType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The supplied property is not declared on a type..
        /// </summary>
        internal static string BulkWriter_Setup_SqlBulkCopyDisposed
        {
            get
            {
                return ResourceManager.GetString("BulkWriter_Setup_SqlBulkCopyDisposed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The supplied property is not declared on a type..
        /// </summary>
        internal static string EnumerableDataReader_GetString_OrdinalDoesNotMapToProperty
        {
            get
            {
                return ResourceManager.GetString("EnumerableDataReader_GetString_OrdinalDoesNotMapToProperty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The supplied property is not declared on a type..
        /// </summary>
        internal static string EnumerableDataReader_GetBytes_OrdinalDoesNotMapToProperty
        {
            get
            {
                return ResourceManager.GetString("EnumerableDataReader_GetBytes_OrdinalDoesNotMapToProperty", resourceCulture);
            }
        }
    }
}
