name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup dotnet 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Setup dotnet 8.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.100'
    - name: Setup required dependencies
      run: ./Setup.ps1
      shell: pwsh    
    - name: Build and Test
      run: ./Build.ps1
      shell: pwsh
    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: artifacts/**/*