# https://github.com/actions/stale

name: "Stale issue & PR handler"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

env:
  ISSUES_DAYS_BEFORE_CLOSE: 14
  PR_DAYS_BEFORE_CLOSE: 14
  ISSUES_DAYS_BEFORE_STALE: 60
  PR_DAYS_BEFORE_STALE: 28

jobs:
  issues:
    name: "Close stale issues and PRs"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/stale@v6.0.0"
        with:
          stale-issue-label: "stale"
          stale-issue-message: "This issue is stale because it has been open ${{ env.ISSUES_DAYS_BEFORE_STALE }} days with no activity. Remove stale label or comment or this will be closed in ${{ env.ISSUES_DAYS_BEFORE_CLOSE }} days."
          close-issue-message: 'This issue was closed because it has been stalled for ${{ env.ISSUES_DAYS_BEFORE_CLOSE }} days with no activity.'
          days-before-close: "${{ env.ISSUES_DAYS_BEFORE_CLOSE }}"
          days-before-stale: "${{ env.ISSUES_DAYS_BEFORE_STALE }}"
          exempt-issue-assignees: true
          exempt-issue-labels: 'awaiting-approval,work-in-progress,up-for-grabs'
          stale-pr-label: "stale"
          stale-pr-message: 'This PR is stale because it has been open ${{ env.PR_DAYS_BEFORE_STALE }} days with no activity. Remove stale label or comment or this will be closed in ${{ env.PR_DAYS_BEFORE_CLOSE }} days.'
          close-pr-message: 'This PR was closed because it has been stalled for ${{ env.PR_DAYS_BEFORE_CLOSE }} days with no activity.'
          days-before-pr-close: "${{ env.PR_DAYS_BEFORE_CLOSE }}"
          days-before-pr-stale: "${{ env.PR_DAYS_BEFORE_STALE }}"
          exempt-all-pr-assignees: true
          exempt-pr-labels: 'awaiting-approval,work-in-progress'